### ISSUE TITLE
找相似向量的回答

### ISSUE THREAD

**Issue by ZhengZixiang** [KaiyuanGao/Kick_AI_Interview#1]
文档里有个千万向量找相似向量，答聚类做法不是太完美，我实习中学到的实现，会做tpo k的近似最近邻。具体说来就是用局部敏感哈希LSH做降维分桶，然后落在同一个哈希桶里的取相似，比如问句匹配就会这么干

**Comment by KaiyuanGao** [comment]
get，我稍后再看下 添加进去
